# Generated by Django 4.2.7 on 2023-11-21 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tp",
            name="fname",
            field=models.CharField(default="tush", max_length=50),
        ),
        migrations.AddField(
            model_name="tp",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="fname",
            ),
        ),
    ]
