# Generated by Django 4.2.7 on 2023-11-21 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_tp_fname_tp_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tp",
            name="fname",
        ),
        migrations.AlterField(
            model_name="tp",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
