# Generated by Django 4.2.7 on 2023-11-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_tp_fname_alter_tp_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tp",
            name="contact_no",
            field=models.IntegerField(null=True),
        ),
    ]
