# Generated by Django 4.2.7 on 2023-11-21 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0004_tp_contact_no"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tp",
            new_name="UserDetails",
        ),
    ]
