# Generated by Django 4.2.7 on 2023-11-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_rename_tp_userdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignto",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
